table 'Localized Labels'
	isHidden
	lineageTag: f2477800-a261-466d-b0d2-50603493bf7d

	measure 'My Report Title' = 0
		isHidden
		lineageTag: 97b78ea2-bafc-428f-b9bc-e1641825b57c

	measure 'My Button Caption' = 0
		isHidden
		lineageTag: 0c7dfb66-8323-401b-8ad9-38f66857790f

	measure 'My Visual Title' = 0
		isHidden
		lineageTag: 14164d5f-03c6-4601-8fce-b9f3ea35d03e

	measure Selezioni = 0
		isHidden
		lineageTag: 98d24005-aa17-4de0-9cc3-de18b12a7b22

	measure Ditta = 0
		isHidden
		lineageTag: f8fb38f3-4e47-493e-85a7-92dd25083f8a

	measure Anno = 0
		isHidden
		lineageTag: 76b8fff3-2790-4501-a850-be8e11333b54

	measure Mese = 0
		isHidden
		lineageTag: 2ac36fd7-72f8-4e42-b2fa-900b200fcd8d

	measure 'Data documento' = 0
		isHidden
		lineageTag: c2684651-d4c7-4057-a09c-22621a67e868

	measure 'Data registrazione' = 0
		isHidden
		lineageTag: 21c001cb-22a9-41be-992e-17a904f556e2

	measure 'Capo Area' = 0
		isHidden
		lineageTag: 09e1f283-5e12-48ca-bae1-65839bad9249

	measure Agente = 0
		isHidden
		lineageTag: deca3240-850c-4b06-855a-023176fb4ffa

	measure Zona = 0
		isHidden
		lineageTag: 4495f4a7-458b-4892-b843-73f0eccbbe1c

	measure Cliente = 0
		isHidden
		lineageTag: 6dadc907-1960-496e-a342-f0cb454788f6

	measure Effettivo = 0
		isHidden
		lineageTag: fb0e9201-a118-49f8-b8e7-6acb6579f15b

	measure 'Articolo - Linea di vendita' = 0
		isHidden
		lineageTag: 4eccea4e-b5b7-4a9c-941e-a59967631e30

	measure 'Articolo - Macrofamiglia, Famiglia' = 0
		isHidden
		lineageTag: e066e284-361b-448e-a5ca-b39ec40861af

	measure 'Articolo - Descrizione articolo' = 0
		isHidden
		lineageTag: 3c624bf7-eb28-42e0-b4db-e8a645550834

	measure 'Articolo - Descrizione variante' = 0
		isHidden
		lineageTag: d391d333-b1c0-42d0-9e4a-0e20a7f6e5c9

	column unused
		isHidden
		displayFolder: unused
		lineageTag: b4bdf5f9-065a-4859-af94-aec81d3f6016
		isNameInferred
		sourceColumn: [unused]

	partition Partition = calculated
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

