table 'Translated Localized Labels'
	lineageTag: 7f9c8a6c-7ddf-43bd-82a2-b46bcacedfac

	measure 'My Report Title Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Report Title",
			   "My Report Title"
			)
		lineageTag: 9cc208f9-b0e4-4971-9d3b-24b7a61a36da

	measure 'My Button Caption Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Button Caption",
			   "My Button Caption"
			)
		lineageTag: b4d1e40b-c267-40ad-94ff-169c1c91cc7c

	measure 'My Visual Title Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Visual Title",
			   "My Visual Title"
			)
		lineageTag: 679d2ed2-2a2d-461a-99c5-4d18cde6af41

	measure 'Selezioni Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Selections",
			   "Selezioni"
			)
		lineageTag: 69a4a949-089b-40a7-a0eb-c73ed76177c9

	measure 'Ditta Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Firm",
			   "Ditta"
			)
		lineageTag: ed1e9a35-3042-4d6b-a43e-3bab38ea584a

	measure 'Anno Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Year",
			   "Anno"
			)
		lineageTag: 52701763-5aea-4f3f-8654-e8dde054fa15

	measure 'Mese Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Month",
			   "Mese"
			)
		lineageTag: 3aeef31c-93bb-45a2-848c-f1a1c0a22823

	measure 'Data documento Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Document Date",
			   "Data documento"
			)
		lineageTag: 68384555-91ee-441a-be7b-052e70726bfd

	measure 'Data registrazione Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Registration Date",
			   "Data registrazione"
			)
		lineageTag: 4533a2af-ea22-4ebd-9631-29a5b4e4d666

	measure 'Capo Area Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Area Manager",
			   "Capo Area"
			)
		lineageTag: 60fe4f55-63b2-420a-8513-72a9b2d631f1

	measure 'Agente Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Agent",
			   "Agente"
			)
		lineageTag: 5c93e42e-e1ee-4d8e-8a99-28b330d06975

	measure 'Zona Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Zone",
			   "Zona"
			)
		lineageTag: c1d5c4ce-779f-4ade-886d-97b62c2a2636

	measure 'Cliente Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Customer",
			   "Cliente"
			)
		lineageTag: b06d35cb-f824-4790-956e-22b1d8b8838d

	measure 'Effettivo Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Effective",
			   "Effettivo"
			)
		lineageTag: ded0fca8-8946-4d68-8d3a-7f071cb38f2f

	measure 'Articolo - Linea di vendita Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Sales Line",
			   "Articolo - Linea di vendita"
			)
		lineageTag: 0dd17b79-34cf-4e1d-9ad2-6b21b7ca62f9

	measure 'Articolo - Macrofamiglia, Famiglia Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Macrofamily, Family",
			   "Articolo - Macrofamiglia, Famiglia"
			)
		lineageTag: f95015c3-7cc7-45d9-9f3f-7f046fa357eb

	measure 'Articolo - Descrizione articolo Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Article Description",
			   "Articolo - Descrizione articolo"
			)
		lineageTag: 7f2e53ef-a382-4f9f-ab11-378539990f22

	measure 'Articolo - Descrizione variante Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Variant Description",
			   "Articolo - Descrizione variante"
			)
		lineageTag: b700e385-d4b1-4141-8d84-5468dd55365d

	measure 'Sintesi Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Synthesis",
			   "Sintesi"
			)
		lineageTag: 69007744-c273-4692-a773-03f4e411f945

	measure 'Oridnato Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Ordered",
			   "Oridnato"
			)
		lineageTag: 912eda5a-4f62-41d6-8ba5-1d2898cdd35c

	measure 'Portafoglio Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Wallet",
			   "Portafoglio"
			)
		lineageTag: f65d6671-1063-46db-9068-4fcf1ce8515a

	measure 'Fatturato Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Turnover",
			   "Fatturato"
			)
		lineageTag: fe17a300-9dcf-4393-9361-81786f3a5e9f

	measure 'Data primo target Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "First Target Date",
			   "Data primo target"
			)
		lineageTag: aa8152b8-7e05-4357-b138-56197d901360

	measure 'Data ultimo target Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Last Target Date",
			   "Data ultimo target"
			)
		lineageTag: 4ca769be-91b5-4e25-bf7e-40f162e394db

	measure 'Andamento ordinato e target Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Orderly And Target Trend",
			   "Andamento ordinato e target"
			)
		lineageTag: 40aaa53a-adb3-4966-93d2-26ae3b9e102f

	measure 'Avanzamento sul target Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Progress On The Target",
			   "Avanzamento sul target"
			)
		lineageTag: c064fb6d-9fc0-4ec2-abf2-b17998c3c91d

	measure 'Target Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Target",
			   "Target"
			)
		lineageTag: da58e82a-8fb4-4f54-83e0-4938af23a799

	measure 'Dettaglio Pipeline Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Pipeline Detail",
			   "Dettaglio Pipeline"
			)
		lineageTag: 14de567b-ea83-417d-9a0f-b1622dff8eda

	column unused
		isHidden
		displayFolder: unused
		lineageTag: b4e78ebb-92e2-43b5-a275-a83d91b4e09f
		isNameInferred
		sourceColumn: [unused]

	partition Partition = calculated
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

