table 'Translated Localized Labels'
	lineageTag: eef0a3f2-aa99-44e8-8658-a1f7f82b61b1

	measure 'My Report Title Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Report Title",
			   "My Report Title"
			)
		lineageTag: c8cd5e7d-665c-4102-8358-360cf17ea44b

	measure 'My Button Caption Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Button Caption",
			   "My Button Caption"
			)
		lineageTag: 7dd3a406-2211-4e95-8b1b-495aeca98184

	measure 'My Visual Title Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Visual Title",
			   "My Visual Title"
			)
		lineageTag: 2d595917-9e96-4047-93cf-b3e27b545a06

	measure 'Selezioni Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Selections",
			   "Selezioni"
			)
		lineageTag: 3ef7cf30-7c3a-4b2e-9471-daed8115b57b

	measure 'Ditta Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Firm",
			   "Ditta"
			)
		lineageTag: 83fff49c-90e0-46db-aa6e-ffd9836536bb

	measure 'Anno Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Year",
			   "Anno"
			)
		lineageTag: a6e9afcc-5ca9-4bdc-bfd3-da06a3012f83

	measure 'Mese Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Month",
			   "Mese"
			)
		lineageTag: a6620534-b732-459d-b719-76f7209ce8e5

	measure 'Data documento Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Document Date",
			   "Data documento"
			)
		lineageTag: a95fd053-b448-4cbe-b370-bcafbb1bde00

	measure 'Data registrazione Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Registration Date",
			   "Data registrazione"
			)
		lineageTag: c1c65632-426c-4aa3-9335-9d063a034f64

	measure 'Capo Area Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Area Manager",
			   "Capo Area"
			)
		lineageTag: 8c102c9d-33d0-46be-9861-d71181393901

	measure 'Agente Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Agent",
			   "Agente"
			)
		lineageTag: ae5e4a7f-731c-4550-b258-11b2856f4c6b

	measure 'Zona Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Zone",
			   "Zona"
			)
		lineageTag: b080e3c6-9472-4675-9df4-af784c8c25c2

	measure 'Cliente Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Customer",
			   "Cliente"
			)
		lineageTag: c960412f-9b74-4769-ae48-5812b7abe8db

	measure 'Effettivo Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Effective",
			   "Effettivo"
			)
		lineageTag: 8d83bd1d-777a-4e78-8122-2319b67ca5d2

	measure 'Articolo - Linea di vendita Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Sales Line",
			   "Articolo - Linea di vendita"
			)
		lineageTag: be85fa9a-0c6f-4bf3-be34-be4decec1b58

	measure 'Articolo - Macrofamiglia, Famiglia Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Macrofamily, Family",
			   "Articolo - Macrofamiglia, Famiglia"
			)
		lineageTag: 4c5e59ed-ac55-44ed-8ca9-75eb16b1281e

	measure 'Articolo - Descrizione articolo Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Article Description",
			   "Articolo - Descrizione articolo"
			)
		lineageTag: 65bdd427-eb61-41b3-9c7b-43e36ebbc500

	measure 'Articolo - Descrizione variante Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Variant Description",
			   "Articolo - Descrizione variante"
			)
		lineageTag: 2fb8dbe4-cacb-49d6-9f5b-1b751f70b2be

	column unused
		isHidden
		displayFolder: unused
		lineageTag: c482da3f-d987-4cfd-a797-a727559dc4fa
		isNameInferred
		sourceColumn: [unused]

	partition Partition = calculated
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

