table 'Translated Localized Labels'
	lineageTag: d12c185c-ebbb-4087-9db3-2d72860c3a4c

	measure 'My Report Title Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Report Title",
			   "My Report Title"
			)
		lineageTag: 3f0dc965-a442-461d-ba93-8f48b81f62c4

	measure 'My Button Caption Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Button Caption",
			   "My Button Caption"
			)
		lineageTag: 8424af90-8036-4380-9db8-b9bfe50aaf33

	measure 'My Visual Title Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Visual Title",
			   "My Visual Title"
			)
		lineageTag: f2c28411-f967-4a89-95cb-4dd23e5de725

	measure 'Selezioni Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Selections",
			   "Selezioni"
			)
		lineageTag: b5db3b32-bc09-486a-94f1-a6d46fc28825

	measure 'Ditta Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Firm",
			   "Ditta"
			)
		lineageTag: 546112da-5842-4ef8-9a4b-5f663d155ee2

	measure 'Anno Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Year",
			   "Anno"
			)
		lineageTag: b8b683cd-fe5b-4166-acb6-4a55d22bf2ef

	measure 'Mese Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Month",
			   "Mese"
			)
		lineageTag: 044b503a-e419-467e-93c5-54867b2d4d0e

	measure 'Data documento Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Document Date",
			   "Data documento"
			)
		lineageTag: eb628ce4-00f3-4070-98c9-b6d66aa4f947

	measure 'Data registrazione Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Registration Date",
			   "Data registrazione"
			)
		lineageTag: 5894ef9d-f43c-4af6-9c84-ae34fe703f9a

	measure 'Capo Area Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Area Manager",
			   "Capo Area"
			)
		lineageTag: 2cf0f09f-165b-40a4-8e32-9702d6b20ae5

	measure 'Agente Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Agent",
			   "Agente"
			)
		lineageTag: 30c8883d-2cb9-4f9c-b441-7dfcd925470a

	measure 'Zona Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Zone",
			   "Zona"
			)
		lineageTag: 95edebf6-50cd-4f05-8f4a-55e78dc799a4

	measure 'Cliente Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Customer",
			   "Cliente"
			)
		lineageTag: 48578ee6-576e-4bc7-bfc7-35ad207a72e3

	measure 'Effettivo Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Effective",
			   "Effettivo"
			)
		lineageTag: b1eac07f-55d6-4746-905b-1a63d258e94b

	measure 'Articolo - Linea di vendita Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Sales Line",
			   "Articolo - Linea di vendita"
			)
		lineageTag: 4e0c1652-1a62-478f-bf8e-5a3d1ede295e

	measure 'Articolo - Macrofamiglia, Famiglia Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Macrofamily, Family",
			   "Articolo - Macrofamiglia, Famiglia"
			)
		lineageTag: b066cdea-9910-4d57-8de7-65c9511dd8dd

	measure 'Articolo - Descrizione articolo Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Article Description",
			   "Articolo - Descrizione articolo"
			)
		lineageTag: 10efda53-d6a0-4227-83f8-57b8291d9569

	measure 'Articolo - Descrizione variante Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Article - Variant Description",
			   "Articolo - Descrizione variante"
			)
		lineageTag: 648d7451-b9a5-4c85-8f53-e8ed09453b12

	measure 'Sintesi Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Synthesis",
			   "Sintesi"
			)
		lineageTag: 54cb4c90-ad81-4b3b-8dd5-e00f5afc7e1d

	measure 'Oridnato Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Ordered",
			   "Oridnato"
			)
		lineageTag: 94f84d9f-1e79-49de-952e-aa48b28e37a9

	measure 'Portafoglio Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Wallet",
			   "Portafoglio"
			)
		lineageTag: c2d98694-4d3e-4e51-8907-363f7f9e9a22

	measure 'Fatturato Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Turnover",
			   "Fatturato"
			)
		lineageTag: 6be6c641-6f70-44be-901b-9584008f2bc9

	measure 'Data primo target Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "First Target Date",
			   "Data primo target"
			)
		lineageTag: 7997f8de-7a7c-4827-9428-343bcc1183c4

	measure 'Data ultimo target Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Last Target Date",
			   "Data ultimo target"
			)
		lineageTag: 15445466-3de3-4f30-a09b-b8cd5e4ad8f5

	measure 'Andamento ordinato e target Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Orderly And Target Trend",
			   "Andamento ordinato e target"
			)
		lineageTag: fe7aec7e-70ac-42e2-951c-e56e98e3bfdb

	measure 'Avanzamento sul target Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Progress On The Target",
			   "Avanzamento sul target"
			)
		lineageTag: 0710bada-ea59-460a-ac8a-d1b0cb5b060f

	measure 'Target Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Target",
			   "Target"
			)
		lineageTag: 4a99e1fb-fa87-4501-ae58-6d915292f2b4

	measure 'Dettaglio Pipeline Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "Pipeline Detail",
			   "Dettaglio Pipeline"
			)
		lineageTag: 84c815d1-a81a-4eec-9b61-f830233d7b9f

	column unused
		isHidden
		displayFolder: unused
		lineageTag: a21f9b02-818b-4626-acac-8ca3834aa31c
		isNameInferred
		sourceColumn: [unused]

	partition Partition = calculated
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

